version: '3.8'

services:
  mysql:
    image: bitnami/mysql:8.0
    ports:
      - '3306:3306'
    volumes:
      - 'mysql_data:/bitnami/mysql/data'
    environment:
      MYSQL_DATABASE: php_db
      MYSQL_USER: php_user
      MYSQL_PASSWORD: php_password
      MYSQL_ROOT_PASSWORD: mysql_root_password
    healthcheck:
      test: [ 'CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh' ]
      interval: 15s
      timeout: 5s
      retries: 6
    restart: unless-stopped
    tty: true
    networks:
      - php_notify_docker
#Docker Networks
networks:
  php_notify_docker:
    driver: bridge
#Volumes
volumes:
  mysql_data:
    driver: local
